name: Despliegue

on:
  push:
    branches: [master]

permissions:
  id-token: write
  contents: read

jobs:
  apply:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra/terraform
    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::349825298324:role/cencosud-reconciliation-dev-github
          aws-region: us-east-2

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.8

      - run: terraform init -input=false
      - run: terraform apply -auto-approve -input=false
